### ISSUE TITLE
Trybash.org Domain

### ISSUE THREAD

**Issue by grekko** [trybash/trybash.github.io#1]
Currently @ljdursi owns the trybash.org domain. In case he has no use for it we might have a chance to get it for our project.

**Comment by ljdursi** [comment]
Hi - Sorry, I know it looks unused right now, but a colleague and I have something almost ready to go that will be using that domain.

**Comment by grekko** [comment]
Hi Jonathan, thanks for the heads up. I am excited to see what you guys are going to publish. In case you'll change your mind for whatever reason and dont need the domain we would appreciate to hear from you.

So we will settle with http://trybash.github.io/ for now.
